### ISSUE TITLE
Consider removing django-simple-captcha from the requirements

### ISSUE THREAD

**Issue by batisteo** [divio/aldryn-forms#146]
Could you please consider removing 'django-simple-captcha' from the `REQUIREMENTS` list, and adding this to the `setup.py`:

```python
extras_require={'captcha': ['django-simple-captcha']},
```

And advise users to install with: `pip install aldryn-forms[captcha]`

--- 
This because I would need to use https://github.com/praekelt/django-recaptcha and the package name is similar (`captcha`).

---

Also update we can update the readme to include the urls step.

**Comment by theitsmith** [comment]
I tend to prefer that it's integrated as it has no external dependencies otherwise (i.e. for using captcha functionality; whereas recaptcha requires additional setup with Google.

Perhaps another approach might work?

What about renaming the app for django-recaptcha from 'captcha' to 'recaptcha'? This is a little clearer as well as it clearly identifies the purpose of the app (since 'recaptcha' refers to a specific external project).

django-simple-captcha could be similarly renamed from 'captcha' to 'simple-captcha'. Again, it more clearly identifies the installed app--currently, seeing the installed app 'captcha' listed wouldn't really identify exactly which captcha app is installed.

To take it a step further, there are other changes that may be necessary as well--such as URL patterns, or things where their names may collide (simple-captcha users a '^captcha/' URL patter, not sure what or if django-recaptcha does the same).

These changes (or change requests or PRs) belong upstream though. 🙂

**Comment by macolo** [comment]
I have the same problem. Probably nobody is using simple-captcha anymore in 2019.

**Comment by macolo** [comment]
This is outrageous: https://github.com/praekelt/django-recaptcha/issues/87

**Comment by macolo** [comment]
Here is a pull request that would solve the problem: https://github.com/divio/aldryn-forms/pull/94

the simple captcha plugin should be a separate package (also in aldryn).

We can contribute the google recaptcha plugin as a separate package once this is solved.

**Comment by macolo** [comment]
Here is the recaptcha plugin for aldryn forms - it's currently blocked by this issue.

https://gitlab.com/what-digital/aldryn-forms-recaptcha-plugin/

**Comment by macolo** [comment]
https://github.com/divio/aldryn-forms/commit/76ba720e8be85967d71a48181eee4582f6d7af14

**Comment by victor-yunenko** [comment]
Yes it was removed, not on pypi though since I'm unable to access it. Still since most of us are using github release tags now I'm closing this ticket.
