### ISSUE TITLE
What is a working requirements.txt for thhis project?

### ISSUE THREAD

**Issue by kiwiheretic** [divio/aldryn-forms#163]
I tried a vanilla install of djangocms (3.5.2) but when I "pip install aldryn-forms" I get this error:

djangocms-column 1.7.0 has requirement django<1.10,>=1.8, but you'll have django 1.11.13 which is incompatible.
django-simple-captcha 0.5.9 has requirement Pillow!=5.1.0,>=2.2.2, but you'll have pillow 5.1.0 which is incompatible.

I've tried manually downgrading package versions but then other things conflict.  Would someone like to share their output from "pip freeze" ?

**Comment by wfehr** [comment]
It doesn't seem like you installed a "vanilla django-cms" tbh, because 'djangocms-column' is not included if you just install the cms itself. I made a virtualenv and installed django-cms + aldryn-forms, resulting in the following requirements.txt:

> aldryn-boilerplates==0.7.7
aldryn-forms==3.0.3
certifi==2018.4.16
chardet==3.0.4
cssselect==1.0.3
cssutils==1.0.2
Django==1.11.14
django-absolute==0.3
django-appconf==1.0.2
django-classy-tags==0.8.0
django-cms==3.5.2
django-emailit==0.2.3
django-filer==1.3.2
django-formtools==2.1
django-mptt==0.8.7
django-polymorphic==2.0.2
django-ranged-response==0.2.0
django-sekizai==0.10.0
django-simple-captcha==0.5.9
django-sizefield==0.9.1
django-tablib==3.2
django-treebeard==4.3
djangocms-admin-style==1.2.8
djangocms-attributes-field==0.3.0
djangocms-text-ckeditor==3.6.0
easy-thumbnails==2.5
et-xmlfile==1.0.1
html5lib==0.9999999
idna==2.7
jdcal==1.4
lxml==4.2.3
odfpy==1.3.6
openpyxl==2.4.9
Pillow==5.2.0
premailer==3.2.0
pytz==2018.5
PyYAML==3.12
requests==2.19.1
six==1.11.0
tablib==0.12.1
unicodecsv==0.14.1
Unidecode==0.4.21
urllib3==1.23
xlrd==1.1.0
xlwt==1.3.0
YURL==0.13

**Comment by kiwiheretic** [comment]
Ok, I've managed to prove it's a vanilla install.  Here is a snipper of my pip freeze

(djangocms) dev@f9ddb4c0a19e:~/site$ pip freeze | grep column
djangocms-column==1.7.0
(djangocms) dev@f9ddb4c0a19e:~/site$ 

and the entire Dockerfile for recreating the docker image is:

FROM ubuntu:17.10
EXPOSE 80/tcp
ENV TERM xterm-256color
RUN apt update && apt install -y apt-utils dialog && \
 apt install -y python3-dev python3-pip virtualenv && \
 useradd --uid 102 --home-dir /home/dev dev && \
 mkdir /home/dev && \
 chown dev.dev /home/dev
USER dev
RUN cd && virtualenv --python=python3 ~/venv/djangocms && \
 ( . ~/venv/djangocms/bin/activate && pip install --upgrade pip && \
  pip install djangocms-installer && mkdir site && cd site && djangocms -f -p . mysite && \
  pip install aldryn-forms && pip freeze | grep column )
CMD ["/bin/bash"]

Hence a build failure with a clean install.

It's also interesting to note that the supposedly problematic package djangocms-columns was installed after the execution of "pip install aldryn-forms" and not the cms itself.

**Comment by victor-yunenko** [comment]
That ticket appears to be resolved already. I'll close it now, please feel free to reopen if the issue persists.
