### ISSUE TITLE
Django CMS 3.4 LTS not supported???

### ISSUE THREAD

**Issue by jedie** [divio/aldryn-forms#184]
setup.py used `django-cms>=3.5` ... So, Django CMS 3.4 LTS is not supported???

Why? And it's missing in https://github.com/divio/aldryn-forms/blob/master/CHANGELOG.rst

**Comment by mjlabe** [comment]
According to the docs, Django CMS 3.4.x does not support Django 2.x. Due to the relatively large amount of changes in Django 2.x, I imagine the developer couldn't keep backwards compatibility. I'm sure you can still use older releases. 

http://docs.django-cms.org/en/latest/#software-version-requirements-and-release-notes

**Comment by victor-yunenko** [comment]
Closing as it appears to be no longer actual - django 1.11 is deprecated now along with cms 3.4 :)
